# Generated by Django 5.1.4 on 2024-12-05 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 13, 4, 25, 799386)),
        ),
    ]
