# Generated by Django 5.1.4 on 2024-12-05 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_post_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 13, 28, 33, 867299)),
        ),
    ]
